---
- name: Set clock timezone on Cisco IOS devices and save config
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure log timestamp format
      cisco.ios.ios_config:
        lines:
          - service timestamps log datetime msec localtime show-timezone

    - name: Save configuration
      cisco.ios.ios_command:
        commands:
          - write memory
