---
- name: Set clock timezone on Cisco IOS devices and save config
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure clock timezone
      cisco.ios.ios_config:
        lines:
          - clock timezone AQTT 5 0

    - name: Save configuration (write memory)
      cisco.ios.ios_command:
        commands:
          - write memory
